version: 0.2.0.{build}
branches:
  only:
  - master
os: Visual Studio 2015
configuration: Release
assembly_info:
  patch: true
  file: src\GlobalAssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-alpha'
cache: src\packages
before_build:
- cmd: nuget restore src\Orleans.Activities.sln
build:
  verbosity: minimal
artifacts:
- path: src\Orleans.Activities\bin\Release\Orleans.Activities.???
  name: Binaries