- branches:
    only:
      - master
  version: -{branch}{build}
  install:
  - ps: Set-AppveyorBuildVariable -Name productversion -Value [IO.File]::ReadAllText(".\productversion.txt")
  - ps: Update-AppveyorBuild -Version [IO.File]::ReadAllText(".\productversion.txt") + $version
  os: Visual Studio 2015
  configuration: Debug
  assembly_info:
    patch: true
    file: src\GlobalAssemblyInfo.cs
    assembly_version: $(productversion)
    assembly_file_version: $(productversion)
    assembly_informational_version: $(productversion)-{branch}{build}
  cache: src\packages
  before_build:
  - cmd: nuget restore src\Orleans.Activities.sln
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    verbosity: minimal
- branches:
    only:
      - stable
  version: -{branch}{build}
  install:
  - ps: Set-AppveyorBuildVariable -Name productversion -Value [IO.File]::ReadAllText(".\productversion.txt")
  - ps: Update-AppveyorBuild -Version [IO.File]::ReadAllText(".\productversion.txt") + $version
  os: Visual Studio 2015
  configuration: Release
  assembly_info:
    patch: true
    file: src\GlobalAssemblyInfo.cs
    assembly_version: $(productversion)
    assembly_file_version: $(productversion)
    assembly_informational_version: $(productversion)
  cache: src\packages
  before_build:
  - cmd: nuget restore src\Orleans.Activities.sln
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    verbosity: minimal
