- environment:
    productversion: 0.0.0
  init:
    set /p productversion=<productversion.txt & appveyor SetVariable -Name productversion -Value %productversion%
  version: $(productversion)-{branch}{build}
  branches:
    only:
      - master
  os: Visual Studio 2015
  configuration: Debug
  assembly_info:
    patch: true
    file: src\GlobalAssemblyInfo.cs
    assembly_version: $(productversion)
    assembly_file_version: $(productversion)
    assembly_informational_version: $(productversion)-{branch}{build}
  cache: src\packages
  before_build:
  - cmd: nuget restore src\Orleans.Activities.sln
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    verbosity: minimal
- environment:
    productversion: 0.0.0
  init:
    set /p productversion=<productversion.txt & appveyor SetVariable -Name productversion -Value %productversion%
  version: $(productversion)-{branch}{build}
  branches:
    only:
      - stable
  os: Visual Studio 2015
  configuration: Release
  assembly_info:
    patch: true
    file: src\GlobalAssemblyInfo.cs
    assembly_version: $(productversion)
    assembly_file_version: $(productversion)
    assembly_informational_version: $(productversion)
  cache: src\packages
  before_build:
  - cmd: nuget restore src\Orleans.Activities.sln
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    verbosity: minimal
